# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelguruapp', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rate', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
